# Generated by Django 4.0.3 on 2022-04-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_management', '0003_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
