# Generated by Django 4.0.3 on 2022-04-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_management', '0005_meal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='calory',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='carb',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='fat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='protein',
            field=models.FloatField(null=True),
        ),
    ]
