# Generated by Django 4.0.3 on 2022-05-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_management', '0006_account_calory_account_carb_account_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='calory',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='carb',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='fat',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='protein',
            field=models.FloatField(default=0, null=True),
        ),
    ]
